In [ ]:
#Introduction to NUMPY

#The datatype of NUMPY id ND Arrays
#Arrays are much more efficient to use and occupies less space for programme execution


In [1]:
#Creating NUMPY arrays

import numpy as np #np stands for NUMPY

In [3]:
array_one=np.array([1,2,3,4,5])

array_one

array([1, 2, 3, 4, 5])

In [4]:
type(array_one)

numpy.ndarray

In [5]:
numbers=[9,8,7,6,5]

In [6]:
array_two=np.array(numbers)

array_two

array([9, 8, 7, 6, 5])

In [7]:
array_of_zeros = np.zeros((3,4))

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
array_of_ones = np.ones((3,3)) #Internall it will be accepting the data as float data type

array_of_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arrays_of_ones_int = np.ones((3,4),dtype=np.int16) #int16 is used for type casting

arrays_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [11]:
array_eye=np.eye(3) #Identity matrix or .eye

array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#how to create an empty matrix

array_empty=np.empty((2,3))

array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
#Req: Print only even numbers upto 30 using NUMPY

array_of_evens=np.arange(2,30,2)

array_of_evens




array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [15]:
#Req: Print only odd numbers upto 30 using NUMPY

array_of_odds=np.arange(1,30,2)

array_of_odds

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])