In [1]:
import numpy as np

In [2]:
#printing of numpy arrays
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [3]:
#2D array
b=np.arange(12).reshape(4,3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [4]:
#3D array
c=np.arange(24).reshape(2,3,4)

print(c)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [5]:
#Arithmatic operations

a=np.array([10,10,10])
b=np.array([5,5,5])

In [6]:
a+b

array([15, 15, 15])

In [7]:
a-b

array([5, 5, 5])

In [8]:
a*b

array([50, 50, 50])

In [9]:
a/b

array([2., 2., 2.])

In [10]:
a>20

array([False, False, False])

In [11]:
b>2

array([ True,  True,  True])

In [12]:
#modifiying existing array

a *= 3
a

array([30, 30, 30])

In [13]:
b+=a
b

array([35, 35, 35])

In [14]:
#unary operators

ages=np.array([10,12,15,18,19,20])

#To find the total sum
ages.sum()

94

In [15]:
#To find the min
ages.min()

10

In [16]:
#To find the max
ages.max()

20

In [18]:
Bank_Customers=np.arange(12).reshape(3,4)

Bank_Customers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
#Req is to find the column based sum and row based sum

##axis 0 is columns and axis 1 is rows

Bank_Customers.sum(axis=1) #row based sum

array([ 6, 22, 38])

In [22]:
Bank_Customers.sum(axis=0) #column based sum

array([12, 15, 18, 21])